name: "Alfred Action"
description: "An action to generate a summary of the changes in a pull request using OpenAI's GPT."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to access the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key to access the GPT-3 API."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - run: cd ${{ github.action_path }}
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} --production=true
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} build
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} start
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        exclude: ${{ inputs.exclude }}

branding:
  icon: "aperture"
  color: "green"
